generate-config:
  stage: build
  script:
    - .gitlab-ci/build-ci
  artifacts:
    paths:
      - generated-config-deb.yml
      - generated-config-doc.yml

deb-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config-deb.yml
        job: generate-config

doc-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config-doc.yml
        job: generate-config
