generate-config:
  stage: build
  script:
    - .gitlab-ci/build-ci
  artifacts:
    paths:
      - generated-config-doc.yml
      - generated-config-deb.yml

.doc-pipeline:
  stage: test
  rules:
    - changes:
      - doc/*/**/*
  trigger:
    include:
      - artifact: generated-config-doc.yml
        job: generate-config

deb-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config-deb.yml
        job: generate-config
