product: ucs
release: "3.2"
scope: ucs_3.2-0-errata3.2-1
src: univention-config-registry
fix: 9.0.6-7.455.201403111545
note:
version: [1]
desc: |
  This update fixes the following issues in the Univention Configuration Registry (UCR) package:
  * In some cases the file ownership was not preserved correctly when a file is committed.
  * The program "univention-check-templates" now also checks UCR template files
    for modifications by using the MD5 hash sum managed by dpkg.
bug: [34241,24010]
