product: ucs
release: "3.2"
scope: ucs_3.2-0-errata3.2-3
src: univention-config-registry
fix: 9.0.6-10.472.201408281610
version: [3]
desc: |
  This update fixes the following issue:
  * Skip writing of internal cache during configHandlers.load()
    if the process has no write permission.
bug: [35368]
