product: ucs
release: "4.2"
version: [2]
scope: ucs_4.2-0-errata4.2-2
src: univention-config-registry
fix: 12.0.1-8A~4.2.0.201711081048
desc: |
 This update addresses the following issue(s):
 * The service status of some mail related service has been fixed.
bug: [43555]
