product: ucs
release: "4.4"
version: [4, 5]
scope: ucs_4.4-0-errata4.4-5
src: univention-config-registry
fix: 14.0.0-18A~4.4.0.202007200731
desc: |-
 This update addresses the following issue:
 * Fixed doing `open(..., "rw")`, which is invalid with Python 3.
bug: [51680]
