product: ucs
release: "4.4"
version: [4]
scope: ucs_4.4-0-errata4.4-4
src: univention-config-registry
fix: 14.0.0-14A~4.4.0.202003301052
desc: |
 This update addresses the following issue:
 * Python absolute imports are now used in
   univention.config_registy.interfaces for Python 3 compatibility.
bug: [51021]
