product: ucs
release: "4.4"
version: [4]
scope: ucs_4.4-0-errata4.4-4
src: univention-config-registry
fix: 14.0.0-15A~4.4.0.202004231208
desc: |
 This update addresses the following issue:
 * The Python 3 compatibility has been improved.
bug: [51156]
