product: ucs
release: "4.1"
version: [3]
scope: ucs_4.1-0-errata4.1-3
src: univention-config-registry
fix: 11.0.0-5.500.201610171059
desc: |
 This update addresses the following issue:
   * `univention-check-templates` now checks all files below
     '/etc/univention/' for modifications.
bug: [41735]
