product: ucs
release: "3.2"
scope: ucs_3.2-0-errata3.2-0
src: univention-config-registry
fix: 9.0.5-5.446.201401151242
version: [0]
desc: |
  univention-config has been improved with respect to the
  following points:
  * univention-ldapsearch now accepts standard UDM
    command line options --binddn, --bindpwd and
    --bindpwdfile for authentiaction.
bug: [32560]
erratum: 23
announced: 2014-01-21
