product: ucs
release: "3.2"
scope: ucs_3.2-0-errata3.2-3
src: univention-config-registry
fix: 9.0.6-12.475.201409011603
version: [2,3]
desc: |
  This update fixes the following issue:
  * Skip writing of internal cache during configHandlers.load()
    if the process has no write permission.
  * univention-check-templates has been fixed to correctly handle
    conffiles with spaces.
bug: [35368,35202]
erratum: 189
announced: 2014-09-10
