product: ucs
release: "4.1"
version: [3,4]
scope: ucs_4.1-0-errata4.1-4
src: univention-config-registry
fix: 11.0.0-8.504.201611211702
desc: |
 This update addresses the following issue(s):
 * Make boolean handling more robust; improve multi-threaded load.
bug: [42912]
erratum: 333
announced: 2016-12-01
