product: ucs
release: "4.1"
version: [3]
scope: ucs_4.1-0-errata4.1-3
src: univention-config-registry
fix: 11.0.0-7.503.201610191453
desc: |
 This update addresses the following issue:
 * `univention-check-templates` now checks all files below '/etc/univention/'
   for modifications.
bug: [41735]
announced: 2016-10-20
erratum: 294
