product: ucs
release: "4.1"
version: [3,4]
scope: ucs_4.1-0-errata4.1-4
src: univention-config-registry
fix: 11.0.0-9.505.201612021514
desc: |
 This update addresses the following issue(s):
 * The functionality to manage services has been changed to ignore processes
   running in a Docker container.
bug: [40659]
erratum: 354
announced: 2016-12-14
