product: ucs
release: "4.1"
version: [4]
scope: ucs_4.1-0-errata4.1-4
src: univention-config-registry
fix: 11.0.0-10.506.201702101631
desc: |
 This update addresses the following issue:
 * In preparation for the upgrade to UCS-4.2 a fall-back implementation for
   the function to quote shell command line arguments has been added. This is
   needed to guarantee UCR is working even during the upgrade of the Python
   interpreter.
bug: [43341]
erratum: 390
announced: 2017-02-15
