product: ucs
release: "4.3"
version: [2]
scope: ucs_4.3-0-errata4.3-2
src: univention-config-registry
fix: 13.0.0-6A~4.3.0.201811121038
desc: |
 This update addresses the following issue(s):
 * univention-config-registry modules cannot accidentally get registered
   multiple times anymore.
bug: [35239]
erratum: 358
announced: 2018-12-05
