product: ucs
release: "4.3"
version: [2]
scope: ucs_4.3-0
src: libconfig-inifiles-perl
fix: 2.94-1
desc: |
 This update addresses the following issue:
 * Add new maintained dependency for MariaDB.
bug: [48201]
ignore:
  - version.scope
erratum: 334
announced: 2018-11-28
