product: ucs
release: "4.4"
version: [2]
scope: ucs_4.4-0-errata4.4-2
src: python-oslo.config
fix: 1:3.17.0-3
desc: |
 This update addresses the following issue:
 * The python-oslo.config package has been added to maintained.
bug: [35428]
maintained: true
erratum: 368
announced: 2019-11-20
