product: ucs
release: "4.4"
version: [0]
scope: ucs_4.4-0-errata4.4-0
src: univention-config-registry
fix: 14.0.0-10A~4.4.0.201907111407
desc: |
 This update addresses the following issue(s):
 * UCR templates which generate binary data have been fixed.
   This was broken since errata 167 and could cause crashes
   of the UMC-Server due to corruptly generated translation
   files.
bug: [49775]
erratum: 186
announced: 2019-07-11
