product: ucs
release: "4.4"
version: [4]
scope: ucs_4.4-0-errata4.4-4
src: univention-config-registry
fix: 14.0.0-17A~4.4.0.202005300929
desc: |
 This update addresses the following issues:
 * Fix Python 3 interfaces API to use `ipaddress` from the standard library
   instead of the legacy `ipaddr` module no longer available in Debian 10
   Buster.
 * Move `univention.debhelper` into a separate package to break a build
   dependency cycle.
bug: [51368, 51374]
erratum: 638
announced: 2020-06-24
